### ISSUE TITLE
discord.js v13 버전은 없나요?

### ISSUE THREAD

**Issue by Habai1** [whguswo/discord-musicbot#2]

**Comment by Habai1** [comment]
@whguswo

**Comment by Habai1** [comment]
avconv를 깔아도 이래요

Successfully registered application commands.
Error: FFmpeg/avconv not found!
    at FFmpeg.getInfo (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\prism-media\src\core\FFmpeg.js:143:11)
    at FFmpeg.create (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\prism-media\src\core\FFmpeg.js:156:38)
    at new FFmpeg (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\prism-media\src\core\FFmpeg.js:45:27)
    at Object.transformer (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\@discordjs\voice\dist\index.js:1767:27)
    at C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\@discordjs\voice\dist\index.js:1923:58
    at Array.map (<anonymous>)
    at createAudioResource (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\@discordjs\voice\dist\index.js:1923:39)
    at play (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\manageQueue.js:9:22)
    at Object.execute (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\commands\play.js:129:13)      
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:687
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[10062]: Unknown interaction
    at handleErrors (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:687:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:786:23)
    at async _REST.request (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\discord.js\node_modules\@discordjs\rest\dist\index.js:1218:22)
    at async ChatInputCommandInteraction.reply (C:\Users\PC\Desktop\musicbot-test\discord-musicbot-main\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:111:5) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: '노래를 대기열에 추가합니다!',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
}

Node.js v18.16.1

**Comment by whguswo** [comment]
I think, You should install "FFmpeg" for window and add ffmpeg to window PATH.

**Comment by Habai1** [comment]
@whguswo 님 혹시 반복 모드 추가 가능한가요?

**Comment by Habai1** [comment]
한국 사람인데

**Comment by Habai1** [comment]
디스코드 닉네임 좀 알려주세요 :>

**Comment by Habai1** [comment]
@whguswo 님 혹시 반복 모드 추가 가능한가요?
